:imagesdir: images 
[.text-center]
= IHE Change Proposal

[.text-center]
== Tracking Information
[cols="1,1"]
|===

|IHE Domain/Program
|DEV Domain / Patient Care Device (PCD) Program

|Change Proposal ID:
|CP-DEV-019

|Change Proposal Status:
|Submitted

|Date of last update:
|2026-01-22

|Person Assigned:
|Eldon Metz

|===

[.text-center]
== Change Proposal Summary Information

[cols="1,1"]
|===

2+^|*OBR-7/8 Timestamp Clarifications*

|Submitter’s Name(s) and e-mail address(es):
|Eldon Metz, emetz@innovisionmedical.com

|Submission Date:
|2026-01-22

|Integration Profile(s) affected:
|Point-of-Care Identity Management (PCIM)

|Actor(s) affected:
|Device-Patient Association Consumer +
Device-Patient Association Manager +
Device-Patient Association Reporter

|IHE Technical Framework or Supplement modified:
|PCIM Profile TI (PCIM TI) revision 2.2, dated 2024-12-05

|Volume(s) and Section(s) affected:
|PCIM TI, Section A.1.2.4

2+|Rationale for Change:

During the drafting of CP-DEV-018, it was identified that the OBR-7 and OBR-8 field descriptions required correction, and the accompanying text describing the number of participants needed revision.

This Change Proposal (CP) proposes changes to PCIM TI to implement the profile clarifications and positions for the above issue.

|===

|===

| _Section A.1.2.4 in PCIM TI - OBR - Observation Request_, change the last sentence before Table A.1.2.4-1 to clarify OBR-7 and OBR-8 represent the times of participant involvement:

|===

[.text-left]
[underline]#Existing Text:#

[.text-left]
It gives the timestamp of the beginning of the association (OBR-7), and when it is known, the end of the association (OBR-8).

|===

|===
[.text-left]
[underline]#Proposed Text:#

[.text-left]
It gives the timestamp of the earliest participant involvement (OBR-7) and the latest participant involvement (OBR-8).

|===

| _Section A.1.2.4 in PCIM TI - OBR - Observation Request_, change the paragraph after Table A.1.2.4-1 to clarify OBR-7 and OBR-8 semantics:

|===

[.text-left]
[underline]#Existing Text:#
[.text-left]
The OBR shall also include the timestamp of the earliest participant involvement (OBR-7) and latest participant involvement (OBR-8) for an association or disassociation event report. 
Each report consists of two Participation Information Segments (PRT) and each may have timestamps for their involvement in PRT-11 and/or PRT-12. 
OBR-7 and OBR-8 conveys the range of time of both participants. See Table A.1.2.6-3 and Table A.1.2.6-4 for definitions of the timestamp semantics in PRT-11 and PRT-12. 
The logic for filling in the timestamp values for OBR-7 and OBR-8 is to examine both the PRT segments that will be sent out in the report and set OBR-7 to the earliest timestamp value and OBR-8 to the latest timestamp value. OBR-7 and 8 may contain the same timestamp.

[.text-left]
[underline]#Proposed Text:#
[.text-left]
The OBR shall also include the timestamp of the earliest participant involvement (OBR-7) and latest participant involvement (OBR-8) for an association or disassociation event report. 
Each report consists of two or more Participation Information Segments (PRT) and each may have timestamps for their involvement in PRT-11 and/or PRT-12. 
OBR-7 and OBR-8 conveys the range of time of all participants. See Table A.1.2.6-3 and Table A.1.2.6-4 for definitions of the timestamp semantics in PRT-11 and PRT-12. 
The logic for filling in the timestamp values for OBR-7 and OBR-8 is to examine the PRT segments that will be sent out in the report and set OBR-7 to the earliest timestamp value and OBR-8 to the latest timestamp value. OBR-7 and 8 may contain the same timestamp.
