[.text-center]
= IHE Change Proposal

[.text-center]
== Tracking Information
[cols="1,1"]
|===

|IHE Domain/Program
|DEV Domain / Patient Care Device (PCD) Program

|Change Proposal ID:
|CP-DEV-013

|Change Proposal Status:
|Draft

|Date of last update:
|2024-09-03

|Person Assigned:
|Eldon Metz

|===

[.text-center]
== Change Proposal Summary Information

[cols="1,1"]
|===

2+^|*Require PRT-4.2 Text and PRT-4.3 Name of Coding System Fields to be populated*

|Submitter’s Name(s) and e-mail address(es):
|Eldon Metz emetz@innovisionmedical.com


|Submission Date:
|2024-09-03

|Integration Profile(s) affected:
|Point-of-Care Identity Management (PCIM)

|Actor(s) affected:
|Device-Patient Association Reporter (DPAR) +
Device-Patient Association Manager (DPAM) +
Device-Patient Association Consumer (DPAC)


|IHE Technical Framework or Supplement modified:
|PCIM Profile TI revision 2.1, dated 2024-07-01

|Volume(s) and Section(s) affected:
|Trial Implementation, Multiple Sections

2+|Rationale for Change:

During implementation of actor systems for testing at NA Connectathon 2024, it was noted by multiple vendors that the NIST HL7 v2 Test Tool for PCD would display an error if PRT 4.3 was not populated. It was decided by the WG that the spec shall require PRT 4.3 to be populated with the name of the coding system. Additionally, IHE TF Vol 2 Appendix C.2 CWE Data Type - code with exception Table C.2-1 requires that the Text component also be populated.

|===

|===

| _Section A.1 Communicate and Report Association State - Table A.1.2.6-1: PRT Fields_: _Update Description column for row 4_:

|===

[.text-left]
[.underline]#Existing Description:#
[.text-left]
Participation .

[.text-left]
[.underline]#Proposed Description:#
[.text-left]
Participation. Includes Participation Code, Text and Name of Coding System. See table A.1.2.6-2 for details for code in PRT 4.1. PRT 4.2 shall be set to the same value as PRT 4.1. PRT 4.3 must be set to _HL70912_.

|===

| _A.3 Examples Messages - Example 1_ : _Update to include text and name of coding system for PRT segments:_

|===


[.text-left]
[.underline]#Existing Text:#
[.text-left]
....
MSH|^~\&|CritCare||AssocMgr||20160726123002||ORU^R01^ORU_R01|12d15a9|P|2.6|||AL|AL|USA||||IHE_DEV_051^IHE PCD^1.3.6.1.4.1.19376.1.6.1.51.1^ISO
PID|||AB60001^^^A^PI||Spaniel^C^R^^^^L
PV1||E|3 WEST ICU^3001^1
OBR|||15404652|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726120000|20160726123000
OBX|1|CWE|68487^MDC_ATTR_EVT_COND^MDC||198332^MDC_EVT_ASSOCIATION_PATIENT_DEVICE^MDC||||||F
PRT|1|UC||EQUIP|||||3 WEST ICU^3001^1|MON5588^^231A8456B1CB2366^EUI-64|20160726120000
PRT|2|UC||AUT|58793^Diesel^N||||3 WEST ICU^3001^1||20160726123000
....

[.text-left]
[.underline]#Proposed Text:#
[.text-left]
....
MSH|^~\&|CritCare||AssocMgr||20160726123002||ORU^R01^ORU_R01|12d15a9|P|2.6|||AL|AL|USA||||IHE_DEV_051^IHE PCD^1.3.6.1.4.1.19376.1.6.1.51.1^ISO
PID|||AB60001^^^A^PI||Spaniel^C^R^^^^L
PV1||E|3 WEST ICU^3001^1
OBR|||15404652|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726120000|20160726123000
OBX|1|CWE|68487^MDC_ATTR_EVT_COND^MDC||198332^MDC_EVT_ASSOCIATION_PATIENT_DEVICE^MDC||||||F
PRT|1|UC||EQUIP^EQUIP^HL70912|||||3 WEST ICU^3001^1|MON5588^^231A8456B1CB2366^EUI-64|20160726120000
PRT|2|UC||AUT^AUT^HL70912|58793^Diesel^N||||3 WEST ICU^3001^1||20160726123000
....

|===

| _A.3 Examples Messages - Example 2_ : _Update to include text and name of coding system for PRT segments:_

|===


[.text-left]
[.underline]#Existing Text:#
[.text-left]
....
MSH|^~\&|MonitorGateway||AssocMgr||20160726160000||ORU^R01^ORU_R01|12d1574|P|2.6|||AL|AL|USA||||IHE_DEV_051^IHE PCD\^1.3.6.1.4.1.19376.1.6.1.51.1^ISO
PID|||AB60001^^^A^PI||McMurphy^R^P^^^^L
PV1||E|3 WEST ICU^3001^1
OBR|||15404697|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726160000|20160726160000
OBX|1|CWE|68487^MDC_ATTR_EVT_COND^MDC||198332^MDC_EVT_ASSOCIATION_PATIENT_DEVICE^MDC||||||R
PRT|1|UC||EQUIP|||||3 WEST ICU^3001^1|MON5596^^231A8456B1CB2366^EUI-64|20160726160000
PRT|2|UC||AUT|58796^Ratched^N||||3 WEST ICU^3001^1||20160726160000
....

[.text-left]
[.underline]#Proposed Text:#
[.text-left]
....
MSH|^~\&|MonitorGateway||AssocMgr||20160726160000||ORU^R01^ORU_R01|12d1574|P|2.6|||AL|AL|USA||||IHE_DEV_051^IHE PCD\^1.3.6.1.4.1.19376.1.6.1.51.1^ISO
PID|||AB60001^^^A^PI||McMurphy^R^P^^^^L
PV1||E|3 WEST ICU^3001^1
OBR|||15404697|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726160000|20160726160000
OBX|1|CWE|68487^MDC_ATTR_EVT_COND^MDC||198332^MDC_EVT_ASSOCIATION_PATIENT_DEVICE^MDC||||||R
PRT|1|UC||EQUIP^EQUIP^HL70912|||||3 WEST ICU^3001^1|MON5596^^231A8456B1CB2366^EUI-64|20160726160000
PRT|2|UC||AUT^AUT^HL70912|58796^Ratched^N||||3 WEST ICU^3001^1||20160726160000
....

|===

| _A.3 Examples Messages - Example 3_ : _Update to include text and name of coding system for PRT segments:_

|===


[.text-left]
[.underline]#Existing Text:#
[.text-left]
....
MSH|^~\&|AssocMgr||AssocConsumer||20160726160000||ORU^R01^ORU_R01|12d1599|P|2.6|||AL|AL|USA||||IHE_DEV_052^IHE PCD^1.3.6.1.4.1.19376.1.6.1.52.1^ISO
PID|||AB60001^^^A^PI||McMurphy^R^P^^^^L
PV1||E|3 WEST ICU^3001^1
OBR|||15404697|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726160000|20160726160000
OBX|1|CWE|68487^MDC_ATTR_EVT_COND^MDC||198332^MDC_EVT_ASSOCIATION_PATIENT_DEVICE^MDC||||||F
PRT|1|UC||EQUIP|||||3 WEST ICU^3001^1|MON5596^^231A8456B1CB2366^EUI-64|20160726160000
PRT|2|UC||AUT|58796^Ratched^N||||3 WEST ICU^3001^1||20160726160000
PRT|3|UC||RO|58796^Ratched^N||||3 WEST ICU^3001^1||20160726164500
....

[.text-left]
[.underline]#Proposed Text:#
[.text-left]
....
MSH|^~\&|AssocMgr||AssocConsumer||20160726160000||ORU^R01^ORU_R01|12d1599|P|2.6|||AL|AL|USA||||IHE_DEV_052^IHE PCD^1.3.6.1.4.1.19376.1.6.1.52.1^ISO
PID|||AB60001^^^A^PI||McMurphy^R^P^^^^L
PV1||E|3 WEST ICU^3001^1
OBR|||15404697|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726160000|20160726160000
OBX|1|CWE|68487^MDC_ATTR_EVT_COND^MDC||198332^MDC_EVT_ASSOCIATION_PATIENT_DEVICE^MDC||||||F
PRT|1|UC||EQUIP^EQUIP^HL70912|||||3 WEST ICU^3001^1|MON5596^^231A8456B1CB2366^EUI-64|20160726160000
PRT|2|UC||AUT^AUT^HL70912|58796^Ratched^N||||3 WEST ICU^3001^1||20160726160000
PRT|3|UC||RO^RO^HL70912|58796^Ratched^N||||3 WEST ICU^3001^1||20160726164500
....

|===

| _A.3 Examples Messages - Example 4_ : _Update to include text and name of coding system for PRT segments:_

|===


[.text-left]
[.underline]#Existing Text:#
[.text-left]
....
MSH|^~\&|MonitorGateway||AssocMgr||20160726230000||ORU^R01^ORU_R01|12d1586|P|2.6|||AL|AL|USA||||IHE_DEV_51^IHE PCD^1.3.6.1.4.1.19376.1.6.1.51.1^ISO
PID|||AB60001^^^A^PI||McMurphy^R^P^^^^L
PV1||E|3 WEST ICU^3001^1
OBR|||15404712|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726230000|20160726230000
OBX|1|CWE|68487^MDC_ATTR_EVT_COND^MDC||198334^MDC_EVT_DISASSOCIATION_PATIENT_DEVICE^MDC||||||R
PRT|1|UC||EQUIP|||||3 WEST ICU^3001^1|MON5596^^231A8456B1CB2366^EUI-64||20160726230000
PRT|2|UC||AUT|58796^Ratched^N||||3 WEST ICU^3001^1||20160726230000
....

[.text-left]
[.underline]#Proposed Text:#
[.text-left]
....
MSH|^~\&|MonitorGateway||AssocMgr||20160726230000||ORU^R01^ORU_R01|12d1586|P|2.6|||AL|AL|USA||||IHE_DEV_51^IHE PCD^1.3.6.1.4.1.19376.1.6.1.51.1^ISO
PID|||AB60001^^^A^PI||McMurphy^R^P^^^^L
PV1||E|3 WEST ICU^3001^1
OBR|||15404712|69136^MDC_OBS_ASSOCIATION_PATIENT_DEVICE^MDC|||20160726230000|20160726230000
OBX|1|CWE|68487^MDC_ATTR_EVT_COND^MDC||198334^MDC_EVT_DISASSOCIATION_PATIENT_DEVICE^MDC||||||R
PRT|1|UC||EQUIP^EQUIP^HL70912|||||3 WEST ICU^3001^1|MON5596^^231A8456B1CB2366^EUI-64||20160726230000
PRT|2|UC||AUT^AUT^HL70912|58796^Ratched^N||||3 WEST ICU^3001^1||20160726230000
....






