:imagesdir: images 
[.text-center]
= IHE Change Proposal

[.text-center]
== Tracking Information
[cols="1,1"]
|===

|IHE Domain/Program
|DEV Domain / Patient Care Device (PCD) Program

|Change Proposal ID:
|CP-PCD-NN9

|Change Proposal Status:
|Draft

|Date of last update:
|2024-08-30

|Person Assigned:
|Eldon Metz

|===

[.text-center]
== Change Proposal Summary Information

[cols="1,1"]
|===

2+^|*Device-Patient Association Search*

|Submitter’s Name(s) and e-mail address(es):
|Eldon Metz, emetz@innovisionmedical.com

|Submission Date:
|TBD

|Integration Profile(s) affected:
|Point-of-Care Identity Management (PCIM)

|Actor(s) affected:
|Device-Patient Association Consumer +
Device-Patient Association Manager 

|IHE Technical Framework or Supplement modified:
|PCIM Profile TI revision 2.1, dated 2024-07-01

|Volume(s) and Section(s) affected:
|Trial Implementation, Multiple Sections

2+|Rationale for Change:

Earlier versions of the PCIM trial implementation specification included use-cases that provided the ability to perform analysis of current and retrospective device patient associations. The approach was based on HL7v2 query messaging. During WG sessions it was decided that search capabilities are better matched to FHIR.

This Change Proposal (CP) proposes changes to the specification to include FHIR search support for Device-Patient associations.

|===

|===

| _Section 7.4.2.3_ *Use Case #3: Search for Devices Associated with a Patient*, _add new use case (based on previous)_:

|===
[.text-left]
[underline]#New Text:#
[.text-left]
7.4.2.3 Use Case #3 Search for Devices Associated with a Patient
[.text-left]
7.4.2.3.1  Description
[.text-left]
A Device-Patient Association Search Consumer may search a Device-Patient Association Manager for a
list of devices associated with a particular patient at present or some specified time range.
[.text-left]
7.4.2.3.2
[.text-left]
Applications and other systems may wish to show current or historical displays of device patient associations for a particular patient. The Device-Patient Association Manager responds to a search request by returning matching results based on the patient search criteria.

|===

| _Section 7.4.2.4_ *Use Case #4: Search for Patients Associated with a Device*, _add new use case (based on previous)_:

|===
[.text-left]
[underline]#New Text:#

[.text-left]
7.4.2.4 Use Case #4 Search for Patients Associated with a Device
[.text-left]
7.4.2.4.1  Description
[.text-left]
A Device-Patient Association Search Consumer may query a Device-Patient Association Manager for a
list of patients associated with a particular device, aat present or some specified time range.
[.text-left]
7.4.2.4.2
[.text-left]
Applications and other systems may wish to show current or historical displays of device patient associations for a particular device. The Device-Patient Association Manager responds to a search requeset by returning matching results based on the device search criteria.

|===

| _Section 7.1_ *Figure 7.1-1: PCIM Actor Diagram*, Update to include Device-Patient Association Search Consumer actor and DEV-5X transaction _:

|===
[.text-left]
[underline]#Original Diagram:#

[ditaa]
----
          +------------------+
          |      DPAR        |
          |  Device-Patient  | 
          |  Association     | 
          |   Reporter       |           
          +------------------+           
                    |                  
         DEV-51     |   
      Communicate   |
      Association   |
         State      |
                    |
                    v                  
          +------------------+
          |       DPAM       |
          |  Device-Patient  |            /------------------------------------\
          |    Association   |            | (Optional) DPAM also participates  | 
          |      Manager     |            | in the MEMDMC profile as a MEM     |
          +------------------+            | DMIC actor to obtain configuration |
                 |     ^                  | information.                       |
      DEV-52     |     |     DEV-19       \------------------------------------/
      Report     |     |     Filter
    Association  |     |  Associations
      State      |     |
                 |     |
                 v     :
          +------------------+
          |       DPAC       |
          |  Device-Patient  | 
          |    Association   | 
          |     Consumer     |           
          +------------------+      
----

[.text-left]
[underline]#Proposed Diagram:#

[ditaa]
----
                        +------------------+
                        |        DPAR      |
                        |   Device-Patient | 
                        |    Association   | 
                        |     Reporter     |           
                        +------------------+ 
                                   |                                                          
                        DEV-51     |   
                     Communicate   |
                     Association   |
                        State      |
                                   |
                                   v                  
          +------------------------------------------------+
          |                      DPAM                      |
          |                 Device-Patient                 |            /------------------------------------\
          |                   Association                  |            | (Optional) DPAM also participates  | 
          |                     Manager                    |            | in the MEMDMC profile as a MEM     |
          +------------------------------------------------+            | DMIC actor to obtain configuration |
                 |     ^                       ^                        | information.                       |
      DEV-52     |     |     DEV-19            |    DEV-5X              \------------------------------------/
      Report     |     |     Filter            |    Search
    Association  |     |  Associations         |  Associations
      State      |     |                       |    
                 |     |                       |
                 v     :                       |
          +------------------+        +-----------------+
          |       DPAC       |        |      DPASC      |
          |  Device-Patient  |        |Device-Patient   |
          |    Association   |        |   Association   |
          |     Consumer     |        | Search Consumer |
          +------------------+        +-----------------+
----

